import type { Metadata, Viewport } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import {
  PARENT_SITE_NAME,
  PARENT_SITE_URL,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_TAGLINE,
  SITE_URL,
} from "./siteConfig";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafbfc" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  colorScheme: "light",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} | ${SITE_TAGLINE}`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "autoBlade",
    "multicam podcast editing",
    "AI podcast editor for Mac",
    "automatic multicam sync",
    "on-device transcription",
    "podcast post-production automation",
    "Apple silicon podcast app",
    "fromSilicon",
  ],
  authors: [{ name: "Losh", url: "mailto:losh@fromsilicon.com" }],
  creator: "Losh (losh@fromsilicon.com)",
  publisher: PARENT_SITE_NAME,
  category: "Multimedia Software",
  alternates: {
    canonical: "/",
  },
  icons: {
    icon: [
      { url: "/icons/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-16.png", sizes: "16x16", type: "image/png" },
    ],
    shortcut: "/icons/icon-32.png",
    apple: "/icons/icon-180.png",
  },
  // og:image / twitter:image are generated by opengraph-image.tsx and
  // twitter-image.tsx, so they're intentionally omitted here.
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} | ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} | ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    site: "@fromsf",
    creator: "@fromsf",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // A @graph with stable @ids. The Organization keeps its fromsilicon.com @id
  // so this domain and the main site describe one company, not two; only the
  // WebSite node is specific to autoblade.fromsilicon.com. The product itself
  // (SoftwareApplication) is declared on the page.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${PARENT_SITE_URL}/#organization`,
        name: PARENT_SITE_NAME,
        url: PARENT_SITE_URL,
        logo: {
          "@type": "ImageObject",
          url: `${PARENT_SITE_URL}/favicon_io/android-chrome-512x512.png`,
          width: 512,
          height: 512,
        },
        email: "losh@fromsilicon.com",
        founder: { "@id": `${PARENT_SITE_URL}/#losh` },
        sameAs: [
          "https://x.com/fromsf",
          "https://www.linkedin.com/in/loshanparajuli/",
          "https://substack.com/@fromsilicon",
        ],
      },
      {
        "@type": "Person",
        "@id": `${PARENT_SITE_URL}/#losh`,
        name: "Losh Parajuli",
        alternateName: "Losh",
        url: "https://www.linkedin.com/in/loshanparajuli/",
        email: "losh@fromsilicon.com",
        jobTitle: "Founder",
        worksFor: { "@id": `${PARENT_SITE_URL}/#organization` },
        sameAs: [
          "https://x.com/fromsf",
          "https://www.linkedin.com/in/loshanparajuli/",
          "https://substack.com/@fromsilicon",
        ],
      },
      {
        "@type": "WebSite",
        "@id": `${SITE_URL}/#website`,
        url: SITE_URL,
        name: SITE_NAME,
        description: SITE_DESCRIPTION,
        publisher: { "@id": `${PARENT_SITE_URL}/#organization` },
        inLanguage: "en",
      },
    ],
  };

  return (
    <html lang="en" className={`${inter.variable} ${instrumentSerif.variable}`}>
      {/* Browser extensions (e.g. Bitdefender) inject attributes like
          `bis_register` / `__processed_*` into <body> before React hydrates,
          which would otherwise trigger a hydration mismatch warning. */}
      <body suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {children}
      </body>
    </html>
  );
}
