import type { Metadata, Viewport } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import {
  CONTACT_EMAIL,
  PARENT_SITE_NAME,
  PARENT_SITE_URL,
  SITE_DESCRIPTION,
  SITE_DESCRIPTION_LONG,
  SITE_NAME,
  SITE_SUMMARY,
  SITE_TITLE,
  SITE_URL,
} from "./siteConfig";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafbfc" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
  colorScheme: "light",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  // Keywords are not a ranking signal for Google, but they are read by
  // several answer engines and site-search tools, so the list mirrors the
  // phrases the page actually earns rather than padding out a wish list.
  keywords: [
    "autoBlade",
    "multicam podcast editor",
    "AI podcast editing software",
    "automatic multicam sync",
    "podcast editor for Mac",
    "on-device transcription",
    "automatic speaker detection",
    "podcast post-production automation",
    "Apple silicon video editor",
    "vertical shorts from podcast",
    "fromSilicon",
  ],
  authors: [{ name: "Losh Parajuli", url: PARENT_SITE_URL }],
  creator: "Losh Parajuli",
  publisher: PARENT_SITE_NAME,
  category: "Multimedia Software",
  alternates: {
    canonical: "/",
    // Standards-based discovery for /llms.txt. An LLM or agent that fetches
    // the page can follow this instead of guessing the path, and it costs a
    // single <link> rather than a non-standard robots.txt directive.
    types: {
      "text/plain": [
        { url: "/llms.txt", title: `${SITE_NAME} — plain-text summary for LLMs` },
      ],
    },
  },
  icons: {
    icon: [
      { url: "/icons/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-16.png", sizes: "16x16", type: "image/png" },
    ],
    shortcut: "/icons/icon-32.png",
    apple: "/icons/icon-180.png",
  },
  // og:image / twitter:image are generated by opengraph-image.tsx and
  // twitter-image.tsx, so they're intentionally omitted here.
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: SITE_TITLE,
    // Social cards have more room than a SERP snippet, so they get the
    // longer copy rather than the truncated-for-Google one.
    description: SITE_DESCRIPTION_LONG,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION_LONG,
    site: "@fromsf",
    creator: "@fromsf",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // A @graph with stable @ids. The Organization keeps its fromsilicon.com @id
  // so this domain and the main site describe one company, not two; only the
  // WebSite node is specific to autoblade.fromsilicon.com. The product itself
  // (SoftwareApplication) is declared on the page.
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${PARENT_SITE_URL}/#organization`,
        name: PARENT_SITE_NAME,
        url: PARENT_SITE_URL,
        logo: {
          "@type": "ImageObject",
          url: `${PARENT_SITE_URL}/favicon_io/android-chrome-512x512.png`,
          width: 512,
          height: 512,
        },
        email: CONTACT_EMAIL,
        founder: { "@id": `${PARENT_SITE_URL}/#losh` },
        sameAs: [
          "https://x.com/fromsf",
          "https://www.linkedin.com/in/loshanparajuli/",
          "https://substack.com/@fromsilicon",
        ],
      },
      {
        "@type": "Person",
        "@id": `${PARENT_SITE_URL}/#losh`,
        name: "Losh Parajuli",
        alternateName: "Losh",
        url: "https://www.linkedin.com/fromsilicon/",
        email: CONTACT_EMAIL,
        jobTitle: "founder",
        worksFor: { "@id": `${PARENT_SITE_URL}/#organization` },
        sameAs: [
          "https://x.com/fromsf",
          "https://www.linkedin.com/in/loshanparajuli/",
          "https://substack.com/@fromsilicon",
        ],
      },
      {
        "@type": "WebSite",
        "@id": `${SITE_URL}/#website`,
        url: SITE_URL,
        name: SITE_NAME,
        // The plain-language "what is this" sentence, so an answer engine
        // that quotes the site node quotes something self-contained.
        description: SITE_SUMMARY,
        publisher: { "@id": `${PARENT_SITE_URL}/#organization` },
        inLanguage: "en",
      },
    ],
  };

  // Browser extensions inject attributes before React hydrates — Bitdefender
  // adds `bis_register` / `__processed_*` to <body>, others add markers like
  // `crxlauncher` to <html>. Left unsuppressed, the mismatch makes React
  // re-render the tree client-side, which interrupts the in-flight GSAP
  // reveals and can strand sections at opacity 0.
  return (
    <html
      lang="en"
      className={`${inter.variable} ${instrumentSerif.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {children}
      </body>
    </html>
  );
}
